module.exports = {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  rules: {
    'at-rule-disallowed-list': ['extend'],
    'at-rule-no-vendor-prefix': true,

    // See:
    // https://github.com/stylelint/stylelint/issues/5133
    // https://github.com/stylelint/stylelint/pull/5202#issuecomment-830668530
    // TODO: In the future @import statements have to be replaced by @use:
    // https://sass-lang.com/documentation/at-rules/import
    'no-invalid-position-at-import-rule': null,
    'media-feature-name-no-vendor-prefix': true,
    'property-no-vendor-prefix': true,
    'selector-no-vendor-prefix': true,
    'value-no-vendor-prefix': true,
    'color-hex-length': 'long',
    'comment-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'declaration-no-important': true,
    'declaration-property-value-disallowed-list': {
      '/^border/': 'none',
    },
    'function-url-quotes': 'always',
    'font-weight-notation': 'numeric',
    'font-family-name-quotes': 'always-where-recommended',
    'max-nesting-depth': 3,
    // Configuration options:
    // https://github.com/hudochenkov/stylelint-order/blob/master/rules/order/README.md
    'order/order': [
      [
        'dollar-variables',
        'custom-properties',
        {
          type: 'at-rule',
          name: 'include',
        },
        'declarations',
        'rules',
        {
          type: 'at-rule',
          name: 'container',
        },
        {
          type: 'at-rule',
          name: 'include',
          parameter: 'up-to|at-least',
        },
        {
          type: 'at-rule',
          name: 'media',
        },
      ],
      {
        unspecified: 'ignore',
        disableFix: true,
      },
    ],
    'order/properties-order': [
      {
        properties: [
          'all',
          'box-sizing',
          'contain',
          'contain-intrinsic-size',
          'contain-intrinsic-width',
          'contain-intrinsic-height',
          'contain-intrinsic-inline-size',
          'contain-intrinsic-block-size',
          'container',
          'container-name',
          'container-type',
          'cx',
          'cy',
          'd',
          'display',
          'appearance',
          'visibility',
          'content-visibility',
          'z-index',
          'paint-order',
          'position',
          'position-anchor',
          'position-area',
          'position-try',
          'position-try-order',
          'position-try-fallbacks',
          'anchor-name',
          'top',
          'right',
          'bottom',
          'left',
          'offset',
          'offset-anchor',
          'offset-distance',
          'offset-path',
          'offset-position',
          'offset-rotate',

          'grid',
          'grid-template-rows',
          'grid-template-columns',
          'grid-template-areas',
          'grid-auto-rows',
          'grid-auto-columns',
          'grid-auto-flow',
          'column-gap',
          'row-gap',
          'grid-area',
          'grid-row',
          'grid-row-start',
          'grid-row-end',
          'grid-column',
          'grid-column-start',
          'grid-column-end',
          'grid-template',
          'flex',
          'flex-grow',
          'flex-shrink',
          'flex-basis',
          'flex-direction',
          'flex-flow',
          'flex-wrap',
          'box-decoration-break',
          'place-content',
          'place-items',
          'place-self',
          'align-content',
          'align-items',
          'align-self',
          'justify-content',
          'justify-items',
          'justify-self',
          'order',
          'aspect-ratio',
          'width',
          'min-width',
          'max-width',
          'height',
          'min-height',
          'max-height',
          'line-clamp',
          '-webkit-text-fill-color',
          '-webkit-text-stroke',
          '-webkit-text-stroke-width',
          '-webkit-text-stroke-color',
          'inline-size',
          'min-inline-size',
          'max-inline-size',
          'block-size',
          'min-block-size',
          'max-block-size',
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
          'margin-inline',
          'margin-inline-start',
          'margin-inline-end',
          'margin-block',
          'margin-block-start',
          'margin-block-end',
          'inset',
          'inset-block',
          'inset-block-end',
          'inset-block-start',
          'inset-inline',
          'inset-inline-end',
          'inset-inline-start',
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'padding-inline',
          'padding-inline-start',
          'padding-inline-end',
          'padding-block',
          'padding-block-start',
          'padding-block-end',
          'float',
          'clear',
          'overflow',
          'overflow-anchor',
          'overflow-block',
          'overflow-clip-margin',
          'overflow-inline',
          'overflow-x',
          'overflow-y',
          'overscroll-behavior',
          'overscroll-behavior-block',
          'overscroll-behavior-inline',
          'overscroll-behavior-x',
          'overscroll-behavior-y',
          'orphans',
          'gap',
          'columns',
          'column-fill',
          'column-rule',
          'column-rule-color',
          'column-rule-style',
          'column-rule-width',
          'column-span',
          'column-count',
          'column-width',
          'object-fit',
          'object-position',
          'transform',
          'transform-box',
          'transform-origin',
          'transform-style',
          'vector-effect',
          'translate',
          'rotate',
          'scale',
          'zoom',

          'border',
          'border-top',
          'border-right',
          'border-bottom',
          'border-left',
          'border-width',
          'border-top-width',
          'border-right-width',
          'border-bottom-width',
          'border-left-width',
          'border-style',
          'border-top-style',
          'border-right-style',
          'border-bottom-style',
          'border-left-style',
          'border-radius',
          'border-top-right-radius',
          'border-top-left-radius',
          'border-bottom-right-radius',
          'border-bottom-left-radius',
          'border-inline',
          'border-inline-color',
          'border-inline-style',
          'border-inline-width',
          'border-inline-start',
          'border-inline-start-color',
          'border-inline-start-style',
          'border-inline-start-width',
          'border-inline-end',
          'border-inline-end-color',
          'border-inline-end-style',
          'border-inline-end-width',
          'border-block',
          'border-block-color',
          'border-block-style',
          'border-block-width',
          'border-block-start',
          'border-block-start-color',
          'border-block-start-style',
          'border-block-start-width',
          'border-block-end',
          'border-block-end-color',
          'border-block-end-style',
          'border-block-end-width',
          'border-color',
          'border-image',
          'border-image-outset',
          'border-image-repeat',
          'border-image-slice',
          'border-image-source',
          'border-image-width',
          'border-top-color',
          'border-right-color',
          'border-bottom-color',
          'border-left-color',
          'border-collapse',
          'border-spacing',
          'border-start-start-radius',
          'border-start-end-radius',
          'border-end-start-radius',
          'border-end-end-radius',
          'outline',
          'outline-color',
          'outline-style',
          'outline-width',
          'outline-offset',

          'backdrop-filter',
          'backface-visibility',
          'background',
          'background-image',
          'background-position',
          'background-position-x',
          'background-position-y',
          'background-size',
          'background-repeat',
          'background-attachment',
          'background-origin',
          'background-clip',
          'background-color',
          'background-blend-mode',
          'box-shadow',
          'isolation',
          'fill',
          'fill-opacity',
          'fill-rule',
          'flood-color',
          'flood-opacity',
          'lighting-color',
          'marker',
          'marker-end',
          'marker-mid',
          'marker-start',
          'x',
          'y',
          'r',
          'rx',
          'ry',
          'stop-color',
          'stop-opacity',
          'stroke',
          'stroke-dasharray',
          'stroke-dashoffset',
          'stroke-linecap',
          'stroke-linejoin',
          'stroke-miterlimit',
          'stroke-opacity',
          'stroke-width',

          'content',
          'quotes',
          'hanging-punctuation',
          'color',
          'color-interpolation',
          'color-interpolation-filters',
          'accent-color',
          'print-color-adjust',
          'forced-color-adjust',
          'color-scheme',
          'caret-color',
          'font',
          'font-style',
          'font-variant',
          'font-weight',
          'src',
          'font-stretch',
          'font-size',
          'size-adjust',
          'line-height',
          'font-family',
          'font-display',
          'font-kerning',
          'font-language-override',
          'font-optical-sizing',
          'font-palette',
          'font-size-adjust',
          'font-synthesis',
          'font-synthesis-weight',
          'font-synthesis-style',
          'font-synthesis-small-caps',
          'font-synthesis-position',
          'font-variant-alternates',
          'font-variant-caps',
          'font-variant-east-asian',
          'font-variant-emoji',
          'font-variant-ligatures',
          'font-variant-numeric',
          'font-variant-position',
          'font-variation-settings',
          'font-feature-settings',
          'alignment-baseline',
          'dominant-baseline',
          'text-anchor',
          'text-autospace',
          'text-box',
          'text-box-trim',
          'text-box-edge',
          'ascent-override',
          'descent-override',
          'line-gap-override',
          'hyphens',
          'hyphenate-character',
          'hyphenate-limit-chars',
          'initial-letter',
          'letter-spacing',
          'line-break',
          'list-style',
          'list-style-image',
          'list-style-position',
          'list-style-type',
          'direction',
          'text-align',
          'text-align-last',
          'text-decoration',
          'text-decoration-line',
          'text-decoration-style',
          'text-decoration-color',
          'text-decoration-thickness',
          'text-decoration-skip-ink',
          'text-emphasis',
          'text-emphasis-style',
          'text-emphasis-color',
          'text-emphasis-position',
          'text-indent',
          'text-justify',
          'text-underline-position',
          'text-underline-offset',
          'text-orientation',
          'text-overflow',
          'text-rendering',
          'text-shadow',
          'text-transform',
          'text-wrap',
          'text-wrap-mode',
          'text-wrap-style',
          'vertical-align',
          'white-space',
          'white-space-collapse',
          'word-break',
          'word-spacing',
          'overflow-wrap',

          'timeline-scope',
          'scroll-timeline',
          'scroll-timeline-name',
          'scroll-timeline-axis',
          'view-timeline',
          'view-timeline-name',
          'view-timeline-axis',
          'view-timeline-inset',
          'animation',
          'animation-duration',
          'animation-timing-function',
          'animation-delay',
          'animation-iteration-count',
          'animation-direction',
          'animation-fill-mode',
          'animation-play-state',
          'animation-name',
          'animation-timeline',
          'animation-composition',
          'animation-range',
          'animation-range-start',
          'animation-range-end',
          'view-transition-name',
          'view-transition-class',
          'mix-blend-mode',
          'break-before',
          'break-after',
          'break-inside',
          'page',
          'caption-side',
          'clip-path',
          'clip-rule',
          'counter-increment',
          'counter-reset',
          'counter-set',
          'cursor',
          'empty-cells',
          'filter',
          'image-orientation',
          'image-rendering',
          'mask',
          'mask-border',
          'mask-border-outset',
          'mask-border-repeat',
          'mask-border-slice',
          'mask-border-source',
          'mask-border-width',
          'mask-clip',
          'mask-composite',
          'mask-image',
          'mask-mode',
          'mask-origin',
          'mask-position',
          'mask-repeat',
          'mask-size',
          'mask-type',
          'opacity',
          'perspective',
          'perspective-origin',
          'pointer-events',
          'resize',
          'scroll-behavior',
          'scroll-margin',
          'scroll-margin-block',
          'scroll-margin-block-end',
          'scroll-margin-block-start',
          'scroll-margin-bottom',
          'scroll-margin-inline',
          'scroll-margin-inline-end',
          'scroll-margin-inline-start',
          'scroll-margin-left',
          'scroll-margin-right',
          'scroll-margin-top',
          'scroll-padding',
          'scroll-padding-block',
          'scroll-padding-block-end',
          'scroll-padding-block-start',
          'scroll-padding-bottom',
          'scroll-padding-inline',
          'scroll-padding-inline-end',
          'scroll-padding-inline-start',
          'scroll-padding-left',
          'scroll-padding-right',
          'scroll-padding-top',
          'scroll-snap-align',
          'scroll-snap-stop',
          'scroll-snap-type',
          'scrollbar-color',
          'scrollbar-gutter',
          'scrollbar-width',
          'shape-image-threshold',
          'shape-margin',
          'shape-outside',
          'shape-rendering',
          'tab-size',
          'table-layout',
          'ruby-align',
          'ruby-overhang',
          'ruby-position',
          'math-depth',
          'math-style',
          'text-combine-upright',
          'touch-action',
          'transition',
          'transition-behavior',
          'transition-delay',
          'transition-duration',
          'transition-property',
          'transition-timing-function',
          'will-change',
          'unicode-bidi',
          'unicode-range',
          'user-select',
          'widows',
          'writing-mode',
        ],
      },
    ],
    'selector-class-pattern': [
      '^[a-z][a-z0-9-_]+$',
      {
        message: 'Expected class selector to be kebab-case or follow BEM __ --',
      },
    ],
    'selector-id-pattern': [
      '^[a-z][a-z0-9-_]+$',
      {
        message: 'Expected id selector to be kebab-case or follow BEM __ --',
      },
    ],
    'selector-attribute-quotes': 'always',
    'selector-max-compound-selectors': 4,
    'selector-max-id': 0,
    'selector-max-specificity': '0,4,1',
    'selector-max-type': [
      1,
      {
        ignoreTypes: ['/fieldset/'],
      },
    ],
    'selector-max-universal': 0,
    'selector-no-qualifying-type': true,
    'no-descending-specificity': null,
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: [
          'global',

          // For webpack support:
          // https://til.hashrocket.com/posts/sxbrscjuqu-share-scss-variables-with-javascript
          'export',
        ],
      },
    ],
    'scss/double-slash-comment-inline': [
      'never',
      {
        ignore: ['stylelint-commands'],
      },
    ],
    'scss/dollar-variable-colon-space-before': 'never',
    'scss/dollar-variable-colon-space-after': 'always-single-line',
    'scss/dollar-variable-empty-line-before': null,
    'scss/double-slash-comment-whitespace-inside': [
      'always',
      {
        severity: 'warning',
      },
    ],
    'scss/selector-no-redundant-nesting-selector': true,
    'value-keyword-case': [
      'lower',
      {
        camelCaseSvgKeywords: true,
      },
    ],
    'length-zero-no-unit': [
      true,
      {
        ignore: ['custom-properties'],
      },
    ],
  },
  // Allow .camelCase for modules
  // See: https://github.com/stylelint/stylelint/issues/3259#issuecomment-656717023
  overrides: [
    {
      files: ['**/*.module.scss'],
      rules: {
        'selector-class-pattern': '^[a-z][a-zA-Z0-9_-]+$',
        'selector-id-pattern': '^[a-z][a-zA-Z0-9_-]+$',
      },
    },
  ],
};
