name: Release
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup pnpm and node
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish-script: pnpm changeset:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
